% make monthly climatologies for terraclimate from the monthly data
% 2026/2/13 (K.Hegewisch)


yearrange = '19912020;
%yearrange = '19812010';


myFile = '/data/obs/obs/gridded/terraclim/MAT/MONTHLY_V1.1/lonlatel.mat';
time= 1:12; %months since Jan
lat= ncread(myFile,'lat');lat = lat(:,1);
lon= ncread(myFile,'lon');lon= lon(1,:)';


VARIABLES = {'tmax';'tmin';'ppt';'srad';'pet';'aet';'def';'soil';'vap';'vpd';'swe';'ws';'q'};
STANDARD_NAMES = {'air_temperature';'air_temperature';'precipitation_amount';...
		'downward_shortwave_flux';...
		'potential_evapotranspiration';...
		'actual_evapotranspiration';...
		'climatic_water_deficit';...
		'soil_moisture';...
		'vapor_pressure';...
		'vapor_pressure_deficit';...
		'snow_water_equivalent';...
		'wind_speed';...
		'runoff';...
		};
DESCRIPTIONS = {'Average Maximum 2-m Temperature';...
		'Average Minimum 2-m Temperature';...
		'Accumulated Precipitation';...
		'Shortwave Radiation';...
		'Reference Evapotranspiration';...
		'Actual Evapotranspiration';...
		'Climatic Water Deficit';...
		'Column Soil Moisture';...
		'Vapor Pressure';...
		'Vapor Pressure Deficit';...
		'Snow Water Equivalent';...
		'Wind Speed';...
		'Runoff';...
		};
INTFORMATS ={'int16';'int16';'int32';'int16';'int32';'int16';'int16';'int16';'int16';'int16';'int32';'int16';'int16'}
UNITS = {'deg C';'deg C';'mm';'W/m2';'mm';'mm';'mm';'mm';'kPa';'kPa';'mm';'m/s';'mm'};
SCALE_FACTORS = [0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1];
ADD_OFFSETS = [-73,-73,0,0,0,0,0,0,0,0,0,0,0];

%get mask for the oceans
maskFile=matfile('/data/obs/obs/gridded/terraclim/MAT/MONTHLY_V1.1/tmin_2013.mat');
d = maskFile.tmindata(:,:,1);
mask = ones(size(d),'single');
f=find(isnan(d));
mask(f) = NaN;

pathDir = '/data/obs/obs/gridded/terraclim/MAT/CLIMOS_V1.1/';

%I think this is the only piece that needs to be run
for varnum=1:length(VARIABLES);
	varname = char(VARIABLES{varnum});
	description = char(DESCRIPTIONS{varnum});
	stname = char(STANDARD_NAMES{varnum});
	units = char(UNITS{varnum});
	scale_factor = SCALE_FACTORS(varnum);
	add_offset = ADD_OFFSETS(varnum);
	intFormat = char(INTFORMATS{varnum});

	myFile=[pathDir,'terra_climo_',yearrange,'.mat'];
	m=matfile(myFile);
	if(strcmp(varname,'q'));
		data = m.(['runoffclimo']);	
	elseif(strcmp(varname,'swe'));
		data = m.(['snowclimo']);	
	else;
		data = m.([varname,'climo']);	
	end;
	data = 	data .* repmat(mask,[1 1 12]);
	FULLFILENAME = ['TerraClimatev1.1_',yearrange,'_',varname,'.nc'];
	make_layer_netcdf_integer(data,lat,lon,time,varname,units,FULLFILENAME,description,scale_factor,add_offset,intFormat);
end;
